### ISSUE TITLE
Not compatible with RRO Beta branch saves

### ISSUE THREAD

**Issue by AMacro** [scottanderson/railroad.studio#10]
RRS is unable to parse the new UE5 RRO save files
"Failed to load: RangeError: buffer length for Uint32Array should be a multiple of 4"

1. In Steam change to Beta branch of RRO
2. Host a server
3. Save the game
4. Load the save into RRS

**Comment by fauxnik** [comment]
Quick question: are you still actively supporting railroad.studio? It was [mentioned on reddit](https://www.reddit.com/r/RailroadsOnline/comments/12t8d7a/comment/jh2uksm/?utm_source=share&utm_medium=web2x&context=3) that you might've given it up. I'm curious to know if you plan on updating it with support for the GVAS version 3 files or if rejecting them is as much as you have planned.

**Comment by scottanderson** [comment]
The reddit post is not accurate, work is currently in progress to add support for GVAS version 3, which is used by UE5.

With that said, because the file format has changed and I do not have a clear idea of exactly what needs to be updated yet, I can not provide an ETA for when the format will be supported at this time.

**Comment by fauxnik** [comment]
That's good enough for me. I'm just glad to hear the info on reddit was wrong, and you are indeed still working on it. Thanks for the insight. Feel free to @ me if there's anything I might be able to do to help.
