### ISSUE TITLE
Maybe add slope map as background

### ISSUE THREAD

**Issue by Tedz62** [scottanderson/railroad.studio#127]
I would like to propose adding a slope map as a background option to aid in planing track placement. I put together a quick slope map in QGIS using a heightmap uploaded by illudedPerception on Discord. The slope map simplifies the planning process of laying track since the new Aurora Map has so many option for routing track to any one industry. The slopes are in percent. I was able plan a route from the gold mine to the smelter and stamp mill in a minute using the slope map. I would have spent a lot of time in-game looking at the terrain and trial and error track laying to get the same result. I'm using a 2 1/2% ruling grade so I made the 2% slope blue which helps me see my slope limit easier. Thanks for keeping Railroad Studio updated, I use it all the time.
![Slope map](https://github.com/scottanderson/railroad.studio/assets/125933603/3b67b643-8a0d-4a8b-ab04-1eed299ee3bc)

**Comment by illudedPerception** [comment]
if you export it as an image or an SVG then do a pull request and wait until Scott makes it work. also you are missing a river going from top right lake to bottom left lake
 
At this moment im takeing a pause from helping the community because the devs don't deserve help from us to keep people playing RO and then get spat,because they don't give 2 shit about the players who cant refund anyways (bad reviews dissepeared too when suddenly they got alot of reviews from 2-6h players not sus at all, anyways the game is gonna be dead with the attitude i saw coming from the devs and what people relayed to me and the attitude i got when i posted a bug report, i got an answer of you built the track too close and the problem got closed yay "FIXED!"
I wish Scott well with the Gvas2 project and maybe in a few days i will calm down and release some images

**Comment by illudedPerception** [comment]
if you export it as an image or an SVG then do a pull request and wait until Scott makes it work. also you are missing a river going from top right lake to bottom left lake

at this moment im a bit pissed, so im not shareing anything, until i think and maybe calm down in the next few days (tho i have 17k x 17k px grey scale height maps and XYZ cords to generate them for all maps)

**Comment by Tedz62** [comment]
Hello illudedPerception,
I had the river included, but not the proper width. The map in the post above was a quick proof of concept. I placed the in-game map over the height map and the river was to the south a little. I think I'll wait until the map update comes out in March before I do much more. I would need to do a better job of digitizing the lakes for the maps to be used by others. I'm going to placing telegraph shacks on the peaks and key points so I can get the coordinates to make sure the contours and in-game map align. Also I noticed the map above indicates a flatter terrain than exist in the map. I was able to keep all track grades at 2.5%, but not as flat as the slope map suggest so I'll have to investigate further. Below is a basic map of the track connecting the gold industries.
![image](https://github.com/scottanderson/railroad.studio/assets/125933603/e79d9596-4637-49ce-9e68-5461f1f1d393)

**Comment by illudedPerception** [comment]
Problem with the alignment is that the in game map image right now was taken from top view (i think, atleast its how i got mine) so its a screenshot afftected by FOV, but the snip&sketch  image you got off RROx server is not affected by FOV cause its generated with XYZ cords, about 1.4 million lines of them if talking about Aurora falls and it took me about 20 min to get the cords. Also because its a snip of the heightmap image and not the full image will compound the alignment problem

**Comment by scottanderson** [comment]
I think this is resolved now with #134. Thanks @illudedPerception
