### ISSUE TITLE
rolling stock added in Gold update

### ISSUE THREAD

**Issue by illudedPerception** [scottanderson/railroad.studio#142]
ive mostly added them but, still a question
`        length: ###,` where do you get this ?

**Comment by scottanderson** [comment]
The method I use is:
1. Place three of the same car type in a row. The duplicate tool in RS can be helpful for setting this up initially.
2. In RO, ensure that the three cars are fully compressed as tightly as the game allows.
3. Use the measure tool to calculate the distance from the origin of one car to the adjacent car.

Having three cars allows you to confirm the measurements is correct by making the same measurement twice. This ensure that the setup was done correctly.

![image](https://github.com/scottanderson/railroad.studio/assets/662325/5cb7431a-b8b6-4eda-9c7b-ccb796fc3f6e)

Note that, although almost all rolling stock is centered about its origin, this is not the case for all cars. Notably, several locomotives appear to overlap their tender because RS doesn't offset the box forward. It should be possible to use a similar method to compress a symmetrical flatcar on either side of an engine and measure how far off of center the engine's origin is, although this isn't something I've put any effort in to doing.
