### ISSUE TITLE
Failure to load save files.

### ISSUE THREAD

**Issue by 0ptera** [scottanderson/railroad.studio#241]
**Attach the save file**
Add the .sav file to a zip, and attach the .zip file to this issue.
[Aurora.zip](https://github.com/user-attachments/files/18076789/Aurora.zip)

**Describe the bug**
Opening save displays Error Message:
Failed to load: Error: Unexpected component type 4 with flags 1

@https://railroad.studio/studio.js:1:279272
Ba@https://railroad.studio/studio.js:1:280193
Oa@https://railroad.studio/studio.js:1:271989
qa/</</l<@https://railroad.studio/studio.js:1:282772
qa/</<@https://railroad.studio/studio.js:1:282975
qa/s/<@https://railroad.studio/studio.js:1:281516

**To Reproduce**
Open attached save with current version.
Did open normally 2 days ago.

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Firefox
- Version: 128.5.1esr (64-Bit)

**Comment by scottanderson** [comment]
This issue was fixed in #239. Your web browser may have an old version of RS cached. You can try holding ctrl while refreshing, which should override the browser's cache in Chrome or Firefox. For other web browsers, you may need to consult the browser's documentation for instructions on how to clear your cache.

**Comment by 0ptera** [comment]
Thanks, it does now load with the Red Mountain Depot placed.
