### ISSUE TITLE
Rolling Stock Duplicating

### ISSUE THREAD

**Issue by Eblancher** [scottanderson/railroad.studio#55]
This would be helpful for players who don't want to spend hours to get a ton of freight cars. Idk how Possible it is for you to do this but let me know if it is something that you will look into.

**Comment by scottanderson** [comment]
To duplicate rolling stock, we first need to find a way for RS to move or place rolling stock in the world. RS does not have terrain data, so the only thing we can go off of is splines.

I think the most elegant way to do this would be to first create a re-rail tool, where you can click on a frame and then click on a spline to move the frame on to the spline. Calculating the new position is the main challenge here.

Once the mechanics are in place to be able to re-rail stock, duplicating stock can be accomplished with a new tool that works the same way as the re-rail tool, but which copies the frame instead of moving it.

**Comment by scottanderson** [comment]
I've merged some changes to naively re-rail rolling stock on to the clicked spline. I have not had time to validate if this works in the game, but I set it up to put cars the same distance above the track that rolling stock naturally sits on straight flat track (1m). This may need to be adjusted to get things working properly, especially for curved or flat track.

**Comment by Eblancher** [comment]
That actually sounds like a good idea
