### ISSUE TITLE
Download button create error and nothing happen

### ISSUE THREAD

**Issue by wolfmg** [scottanderson/railroad.studio#61]
The bug occur on every save type, beta or not, you can modifi everything but as soon as you try to Save/Download it create an error related to weather time  
![error](https://github.com/scottanderson/railroad.studio/assets/144496519/9468cf4f-fe6c-43bd-863a-2cc890981cb1)

**Comment by wolfmg** [comment]
Ive mannaged to found something , for some reason if i DISABLE the Time of day Cycle and i put sunny weather and 60 for weather switch time ( who is not use anymore) i can now download with no error . i dont know of that could hep a bit

**Comment by nomisthenoob** [comment]
iam having the same issue ..make changes to map and it will not download... i will however try what you have done and see if that works

**Comment by scottanderson** [comment]
This is likely a new property related to weather. Please attach a zip of a save file so that I can reproduce the issue and fix it.

**Comment by RichardDastardly** [comment]
Error started since your last commit ( the "do not store property types" one ) - same save would download fine previous to that. This ( from beta ) one loads fine but errors on a download attempt.

Apparently it won't attach, here's a dropbox link - https://www.dropbox.com/scl/fi/j5sy3hwk4qtovcxzpx3e9/1.1-sanity-is-overrated.zip?rlkey=fc8vrpaddmxk7ni2xag3qfr8z&dl=0
